---
title: "fig4 Random-forest classification model precisely predict Nipponbare"
author: "Dairui"
date: "2020/4/2"
output: html_document
---
修改一半一半
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Clean workspace
rm(list=ls()) 
# Load setting and functions
source("../script/stat_plot_functions.R")
# Set output directory
output_dir="./"
```

```{r}
# 读取文件
design = read.table("../data/design.txt", header=T, row.names= 1, sep="\t")

otufile = "sum_f.txt"
otutab =read.table(paste("../data/",otufile,sep = ""),header = T, row.names = 1, sep = "\t")
otutab = otutab[rownames(otutab) != c("Unassigned"),]#删除Unassigned

# 选择地区
sub_design = subset(design, Description %in% c("A50HnCp7r1","A50HnCp7r3","A50HnCp7r5","A50HnCp7r7","A50HnCp7r9","A50HnCp7r11","A50HnCp7r13","A50HnCp7r15","IR24HnCp7r1","IR24HnCp7r3","IR24HnCp7r5","IR24HnCp7r7","IR24HnCp7r9","IR24HnCp7r11","IR24HnCp7r13","IR24HnCp7r15","A50HnSz7r1","A50HnSz7r3","A50HnSz7r5","A50HnSz7r7","A50HnSz7r9","A50HnSz7r11","A50HnSz7r13","A50HnSz7r15","IR24HnSz7r1","IR24HnSz7r3","IR24HnSz7r5","IR24HnSz7r7","IR24HnSz7r9","IR24HnSz7r11","IR24HnSz7r13","IR24HnSz7r15","IR24HnSz7r16","IR24HnSz7r17"))
# 筛选OTU
idx = rownames(sub_design) %in% colnames(otutab)
sub_design = sub_design[idx,]
sub_otu = otutab[, rownames(sub_design)]   

#用随机森林机器学习法建立模型
library(randomForest)

# 转置分类表
otutab_t = as.data.frame(t(sub_otu))

# 设置分类的标准
otutab_t$group = factor(design[rownames(otutab_t),]$genotype, levels= c("IR24","A50"))

# 设置随机数
set.seed(322)

# 进行分类
otutab_t.rf= randomForest(group ~ ., data=otutab_t, importance=TRUE, proximity=TRUE)
print(otutab_t.rf)

# 输出分类判别结果
write.table(otutab_t.rf$confusion, file = "family_confusion.txt", sep = "\t", quote = F, row.names = T, col.names = T)
imp = as.data.frame(round(importance(otutab_t.rf), 2))
imp=imp[order(imp$MeanDecreaseAccuracy,decreasing = F),]
# 输出菌重要性，按MeanDecreaseAccuracy排序
write.table(imp, file = "family_imp.txt", sep = "\t", quote = F, row.names = T, col.names = T)
# 加上科水平注释
system("awk 'NR==FNR{a[$6]=$4} NR>FNR{print $0\"\t\"a[$1]}' ../data/taxonomy_8.txt family_imp.txt | sed '1 s/$/Class/' > family_imp_class.txt")
```

# 交叉验证
```{r}
# 看随机森林的错误率
n = ncol(otutab_t)-1
myotutab_t= otutab_t[1:n]
set.seed(322)
result= rfcv(myotutab_t, otutab_t$group, cv.fold=5, scale = "log", step = 0.9)
with(result, plot(n.var, error.cv, log="x", type="o", lwd=2))
result1 = result

error.cv = data.frame(num = result$n.var, error.1 =  result$error.cv)
# 用另外4组随机数来看错误率，然后绘图
for (i in 323:326){
  print(i)
  set.seed(i)
  result= rfcv(myotutab_t, otutab_t$group, cv.fold=5, scale = "log", step = 0.9)
  error.cv = cbind(error.cv, result$error.cv)
}


## 绘制交叉验证曲线
n.var = error.cv$num
error.cv = error.cv[,2:6]
colnames(error.cv) = paste('err',1:5,sep='.')
err.mean = apply(error.cv,1,mean)
allerr = data.frame(num=n.var,err.mean=err.mean,error.cv)
# number of features selected
optimal = 14

write.table(allerr, file = "family_crosstest.txt", sep = "\t", quote = F, row.names = T, col.names = T)

p = ggplot() + 
  geom_line(aes(x = allerr$num, y = allerr$err.1), colour = 'grey') + 
  geom_line(aes(x = allerr$num, y = allerr$err.2), colour = 'grey') + 
  geom_line(aes(x = allerr$num, y = allerr$err.3), colour = 'grey') + 
  geom_line(aes(x = allerr$num, y = allerr$err.4), colour = 'grey') + 
  geom_line(aes(x = allerr$num, y = allerr$err.mean), colour = 'black') + 
  geom_vline(xintercept = optimal, colour='black', lwd=0.36, linetype="dashed") + 
  coord_trans(x = "log2") +
  scale_x_continuous(breaks = c(1, 2, 5, 10, 20, 30, 50, 100, 200)) + # , max(allerr$num)
  labs(title=paste('Training set (n = ', dim(otutab_t)[1],')', sep = ''), 
       x='Number of families ', y='Cross-validation error rate') + 
  annotate("text", x = optimal, y = max(allerr$err.mean), label=paste("optimal = ", optimal, sep="")) + 
  main_theme
p
ggsave(p, file = "family_crosstest.pdf", width = 89, height = 50, unit = 'mm')
```

# A. 柱状图展示生物标记菌重要性
```{r}
imp = read.table("family_imp_class.txt", header=T, row.names= 1, sep="\t") 
imp = tail(imp, n = optimal)
imp$Family = factor(rownames(imp), levels = rownames(imp))

colourCount = 9
getPalette = colorRampPalette(brewer.pal(8, "Set1"))

p = ggplot(imp, aes(x = Family, y = MeanDecreaseAccuracy, fill = Class)) + 
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = getPalette(colourCount)) +
  coord_flip() + main_theme
p
ggsave(paste("family_top_feautre",".pdf", sep=""), p, width=89 * 1.5, height=50 * 1.5, unit='mm')
```

# B. 看丰度
```{r}
# select randomForest top features
otu_bar = sub_otu[rownames(imp),] 
mean = data.frame(id = rownames(otu_bar), mean=rowMeans(otu_bar))
# Decreasing by mean
mean = arrange(mean, desc(mean))  
otu_bar$Family = rownames(otu_bar)
otu_bar = melt(otu_bar, id.vars = "Family")
# head(otu_bar)
design$sampleID = rownames(design)
otu_bar = merge(otu_bar, design[,c("sampleID","genotype")], by.x="variable", by.y = "sampleID", all.x = T)
# head(otu_bar)

otu_error_bar = summarySE(otu_bar, measurevar="value", groupvars=c("Family","genotype"))
# head(otu_error_bar)

otu_error_bar$Family = factor(otu_error_bar$Family, levels = mean$id)

p = ggplot(otu_error_bar, aes(x=Family, y=value, fill=genotype)) + 
  scale_fill_manual(values = c("#3498db","#f39c12")) +
   geom_bar(position=position_dodge(), stat="identity") +
   geom_errorbar(aes(ymin=value-ci, ymax=value+ci),
                 width=.5,                    # Width of the error bars
                position=position_dodge(.9)) + main_theme
 p=p+theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))
 p
ggsave(paste("family_errorbar",".pdf", sep=""), p, width=100 * 1.5, height=50 * 2, unit='mm')
```


# B.用另外两组验证
```{r}
grouplist = c("A50_Cp","A50_Sz","IR24_Cp","IR24_Sz")
design_sub = subset(design, Description %in% c("A50HnCp7r2","A50HnCp7r4","A50HnCp7r6","A50HnCp7r8","A50HnCp7r10","A50HnCp7r12","A50HnCp7r14","IR24HnCp7r2","IR24HnCp7r4","IR24HnCp7r6","IR24HnCp7r8","IR24HnCp7r10","IR24HnCp7r12","IR24HnCp7r14","A50HnSz7r2","A50HnSz7r4","A50HnSz7r6","A50HnSz7r8","A50HnSz7r10","A50HnSz7r12","A50HnSz7r14","IR24HnSz7r2","IR24HnSz7r4","IR24HnSz7r6","IR24HnSz7r8","IR24HnSz7r10","IR24HnSz7r12","IR24HnSz7r14"))

predict = matrix(0, ncol = 4, nrow = 7)
colnames(predict) = grouplist
column = 7
design_sub$group = paste(design_sub$genotype,"_",design_sub$site, sep = "")
for(i in 1:4) {
  design_sub2 = subset(design_sub, group %in% grouplist[i])
  idx = rownames(design_sub2) %in% colnames(otutab)
  design_sub2 = design_sub2[idx,]
  otutab_sub = otutab[,rownames(design_sub2)]
  otutab_sub=as.data.frame(t(otutab_sub))
  set.seed(322)
  otutab.pred = predict(otutab_t.rf, otutab_sub)
  otutab.pred
  levels(otutab.pred) = c(2, 1)
  j = column - length(otutab.pred)
  predict[, i]= c(as.vector(otutab.pred), rep(NA, j))
}
# 建立验证结果矩阵
matrix = matrix(as.numeric(predict), ncol = 4, nrow = 7)
colnames(matrix) = grouplist
matrix = t(matrix)
colnames(matrix) = paste("rep", 1:7, sep = "")
# 输出验证结果
write.table(matrix, file = "RF_predict_test.txt", quote = F, row.names = T, col.names = T, sep = "\t")
system("sed -i 's/rep1/ID\trep1/;s/\t2/\tIR24/g;s/\t1/\tNipponbare/g' RF_predict_test.txt")


pheatmap(matrix, color = c("#3498db","#f39c12") , cluster_rows = F, cluster_cols = F, cellwidth = 15, cellheight = 12)
pheatmap(matrix, color = c("#3498db","#f39c12") , cluster_rows = F, cluster_cols = F, cellwidth = 15, cellheight = 12,
         filename = "family_test.pdf")
```

